# Generated by Django 3.0.5 on 2020-06-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
