# Generated by Django 3.0.5 on 2020-04-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200407_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=20)),
                ('state', models.BooleanField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
