# Generated by Django 3.0.5 on 2020-06-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_charge_voltage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('state', models.BooleanField()),
                ('value', models.CharField(blank=True, max_length=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Object')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temperature', models.CharField(blank=True, max_length=5)),
                ('humidity', models.CharField(blank=True, max_length=5)),
                ('moisture', models.CharField(blank=True, max_length=5)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.Object')),
            ],
        ),
    ]
