# Generated by Django 3.0.5 on 2020-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_object_sensor_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='humidity',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='moisture',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temperature',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='value',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
