# Generated by Django 3.0.5 on 2020-06-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200609_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensor_name', to='data.Object'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_name', to='data.Object'),
        ),
    ]
